services:
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - "pgsql_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pgsql_data:
    driver: local
